version: "3.8"

services:
  php-fpm:
    container_name: ${PROJECT_NAME}-php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./../:/var/www/
      - ~/.gitconfig:/etc/gitconfig

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
       - ..:/var/www:rw
    depends_on:
      - php-fpm

  postgres:
    container_name: ${PROJECT_NAME}-postgres
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_movieApp:/var/lib/postgresql/data:rw

volumes:
  db_movieApp: